### ISSUE TITLE
Support for Validator node in Azure?

### ISSUE THREAD

**Issue by amarts** [sovrin-foundation/steward-tools#36]
When I ran the Validator node with all the required config, and steps the below section gave error to me:

https://github.com/sovrin-foundation/steward-tools/blob/master/steward_tech_check.py#L94...L100

```
Rule: machine_type_allowed:
    result: FAILED
    details: Found valid machine_type: vm on unsupported technology: microsoft
    action_needed: Found valid machine_type: vm running on Unsupported technology: microsoft
```

Documents do talk about running Validator in Cloud, should we be adding 'microsoft' as valid tech?

**Comment by mgbailey** [comment]
An Azure VM returns "microsoft" as its machine_type. You are correct that
this should be allowed. steward_tech_check.py should be changed accordingly.

Mike

**Comment by amarts** [comment]
On Azure:
```
amar@Sovrin02:~$ dmesg | grep 'Detected virtualization'
[    9.521496] systemd[1]: Detected virtualization microsoft.
```

On AWS:
```
ubuntu@test-machine:~$ dmesg | grep 'Detected virtua'
[    5.983920] systemd[1]: Detected virtualization xen.
```

We already have 'xen' covered!... adding microsoft would solve this issue!
