### ISSUE TITLE
Container should not require ntpd / systemd-timesync

### ISSUE THREAD

**Issue by tsurai** [sovrin-foundation/steward-tools#39]
Container environments do not require ntpd or systemd-timec as they are using the internal internal time of their host system which *hopefully* does the time syncing for them.

I would have made a pull request but am not sure how you want to handle this case. It is not a real PASS as the host might lack time syncing. Maybe issue a warning or keep the result on UNKNOWN with an corresponding info text?

**Comment by WadeBarnes** [comment]
I thing the most appropriate action would be to set the result as `UNKNOWN` and provide the corresponding details along with instructions on how to perform the required checks to confirm.
